### PR TITLE
Fix None when request is not available

### PR DESCRIPTION
**Pull request by lukaszbanasiak**
Object needs to be passed, rather  than string

### CODE REVIEW

**Comment by dessibelle** [comment]
Thanks @lukaszbanasiak, I will have a look shortly.

I guess there was a typo in your comment, it was a bit hard for me to parse. Am I right to read it like this?

> Object need*s* to be pass*ed*, rather ~that~ than url

**Comment by lukaszbanasiak** [comment]
@dessibelle yes, you have right. Other words: method is waiting for File object not string (url attribute of File object)

**Comment by dessibelle** [comment]
Perfect, just let me test it out a bit before merging.

**Comment by lukaszbanasiak** [comment]
Any progress on that?

**Comment by dessibelle** [comment]
Sorry @lukaszbanasiak, I just wanted to make sure things were somewhat backwards compatible. Doesn't seem to be an issue, so I'm merging now.

**Pull request merged**
